export const CREATE_NEW_WORK_EXPERIANCE = "CREATE_NEW_WORK_EXPERIANCE";
export const DELETE_WORK_EXPERIANCE = "DELETE_WORK_EXPERIANCE";
export const UPDATE_WORK_EXPERIANCE = "UPDATE_WORK_EXPERIANCE";
export const FETCH_ALL_WORK_EXPERIANCES = "FETCH_ALL_WORK_EXPERIANCES";
export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING";
export const ERROR = "ERROR";
